### ISSUE TITLE
Allow Users to Edit their WP Profile on a PMPro + BuddyPress Site 

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-buddypress#58]
BuddyPress hijacks the WordPress User Profile edit screen and redirects to the user's BuddyPress profile. Since this integration allows you to have some users without BuddyPress access, we need to make sure to disable that redirect and allow users to edit their profile in the standard `/wp-admin/profile.php` screen. 

We may also want to hide the "Extended Profile" tab from their profile edit page.

**Comment by andrewlimaza** [comment]
This issue is a bit outdated, I've checked the code again and we allow user's to access their own profile on BuddyPress (and edit it) via the BuddyPress/Boss frontend profile page.

We're not hiding the "Extended Profile" tab, but adding notes that this information may be hidden to non-members to clarify this functionality.
